// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model_db.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "model_db.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace sample_projectname {

namespace {

const ::google::protobuf::Descriptor* db_table1_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  db_table1_reflection_ = NULL;
const ::google::protobuf::Descriptor* db_table2_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  db_table2_reflection_ = NULL;
const ::google::protobuf::Descriptor* db_table3_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  db_table3_reflection_ = NULL;
const ::google::protobuf::Descriptor* db_table4_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  db_table4_reflection_ = NULL;
const ::google::protobuf::Descriptor* db_table5_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  db_table5_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_model_5fdb_2eproto() {
  protobuf_AddDesc_model_5fdb_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "model_db.proto");
  GOOGLE_CHECK(file != NULL);
  db_table1_descriptor_ = file->message_type(0);
  static const int db_table1_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(db_table1, field1_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(db_table1, field2_),
  };
  db_table1_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      db_table1_descriptor_,
      db_table1::default_instance_,
      db_table1_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(db_table1, _has_bits_[0]),
      -1,
      -1,
      sizeof(db_table1),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(db_table1, _internal_metadata_),
      -1);
  db_table2_descriptor_ = file->message_type(1);
  static const int db_table2_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(db_table2, field1_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(db_table2, field2_),
  };
  db_table2_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      db_table2_descriptor_,
      db_table2::default_instance_,
      db_table2_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(db_table2, _has_bits_[0]),
      -1,
      -1,
      sizeof(db_table2),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(db_table2, _internal_metadata_),
      -1);
  db_table3_descriptor_ = file->message_type(2);
  static const int db_table3_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(db_table3, field1_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(db_table3, field2_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(db_table3, field3_),
  };
  db_table3_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      db_table3_descriptor_,
      db_table3::default_instance_,
      db_table3_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(db_table3, _has_bits_[0]),
      -1,
      -1,
      sizeof(db_table3),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(db_table3, _internal_metadata_),
      -1);
  db_table4_descriptor_ = file->message_type(3);
  static const int db_table4_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(db_table4, field1_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(db_table4, field2_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(db_table4, field3_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(db_table4, field4_),
  };
  db_table4_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      db_table4_descriptor_,
      db_table4::default_instance_,
      db_table4_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(db_table4, _has_bits_[0]),
      -1,
      -1,
      sizeof(db_table4),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(db_table4, _internal_metadata_),
      -1);
  db_table5_descriptor_ = file->message_type(4);
  static const int db_table5_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(db_table5, field1_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(db_table5, field2_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(db_table5, field3_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(db_table5, field4_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(db_table5, field5_),
  };
  db_table5_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      db_table5_descriptor_,
      db_table5::default_instance_,
      db_table5_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(db_table5, _has_bits_[0]),
      -1,
      -1,
      sizeof(db_table5),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(db_table5, _internal_metadata_),
      -1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_model_5fdb_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      db_table1_descriptor_, &db_table1::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      db_table2_descriptor_, &db_table2::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      db_table3_descriptor_, &db_table3::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      db_table4_descriptor_, &db_table4::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      db_table5_descriptor_, &db_table5::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_model_5fdb_2eproto() {
  delete db_table1::default_instance_;
  delete db_table1_reflection_;
  delete db_table2::default_instance_;
  delete db_table2_reflection_;
  delete db_table3::default_instance_;
  delete db_table3_reflection_;
  delete db_table4::default_instance_;
  delete db_table4_reflection_;
  delete db_table5::default_instance_;
  delete db_table5_reflection_;
}

void protobuf_AddDesc_model_5fdb_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\016model_db.proto\022\022sample_projectname\"+\n\t"
    "db_table1\022\016\n\006field1\030\001 \001(\t\022\016\n\006field2\030\002 \001("
    "\t\"+\n\tdb_table2\022\016\n\006field1\030\001 \001(\t\022\016\n\006field2"
    "\030\002 \001(\t\";\n\tdb_table3\022\016\n\006field1\030\001 \001(\t\022\016\n\006f"
    "ield2\030\002 \001(\t\022\016\n\006field3\030\003 \001(\t\"K\n\tdb_table4"
    "\022\016\n\006field1\030\001 \001(\t\022\016\n\006field2\030\002 \001(\t\022\016\n\006fiel"
    "d3\030\003 \001(\t\022\016\n\006field4\030\004 \001(\t\"[\n\tdb_table5\022\016\n"
    "\006field1\030\001 \001(\t\022\016\n\006field2\030\002 \001(\t\022\016\n\006field3\030"
    "\003 \001(\t\022\016\n\006field4\030\004 \001(\t\022\016\n\006field5\030\005 \001(\t", 357);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "model_db.proto", &protobuf_RegisterTypes);
  db_table1::default_instance_ = new db_table1();
  db_table2::default_instance_ = new db_table2();
  db_table3::default_instance_ = new db_table3();
  db_table4::default_instance_ = new db_table4();
  db_table5::default_instance_ = new db_table5();
  db_table1::default_instance_->InitAsDefaultInstance();
  db_table2::default_instance_->InitAsDefaultInstance();
  db_table3::default_instance_->InitAsDefaultInstance();
  db_table4::default_instance_->InitAsDefaultInstance();
  db_table5::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_model_5fdb_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_model_5fdb_2eproto {
  StaticDescriptorInitializer_model_5fdb_2eproto() {
    protobuf_AddDesc_model_5fdb_2eproto();
  }
} static_descriptor_initializer_model_5fdb_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#ifndef _MSC_VER
const int db_table1::kField1FieldNumber;
const int db_table1::kField2FieldNumber;
#endif  // !_MSC_VER

db_table1::db_table1()
  : ::google::protobuf::Message() , _internal_metadata_(NULL)  {
  SharedCtor();
  // @@protoc_insertion_point(constructor:sample_projectname.db_table1)
}

void db_table1::InitAsDefaultInstance() {
}

db_table1::db_table1(const db_table1& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:sample_projectname.db_table1)
}

void db_table1::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  field1_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  field2_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

db_table1::~db_table1() {
  // @@protoc_insertion_point(destructor:sample_projectname.db_table1)
  SharedDtor();
}

void db_table1::SharedDtor() {
  field1_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  field2_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void db_table1::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* db_table1::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return db_table1_descriptor_;
}

const db_table1& db_table1::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_model_5fdb_2eproto();
  return *default_instance_;
}

db_table1* db_table1::default_instance_ = NULL;

db_table1* db_table1::New(::google::protobuf::Arena* arena) const {
  db_table1* n = new db_table1;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void db_table1::Clear() {
  if (_has_bits_[0 / 32] & 3) {
    if (has_field1()) {
      field1_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_field2()) {
      field2_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool db_table1::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:sample_projectname.db_table1)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string field1 = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_field1()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->field1().data(), this->field1().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "sample_projectname.db_table1.field1");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_field2;
        break;
      }

      // optional string field2 = 2;
      case 2: {
        if (tag == 18) {
         parse_field2:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_field2()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->field2().data(), this->field2().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "sample_projectname.db_table1.field2");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:sample_projectname.db_table1)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:sample_projectname.db_table1)
  return false;
#undef DO_
}

void db_table1::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:sample_projectname.db_table1)
  // optional string field1 = 1;
  if (has_field1()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->field1().data(), this->field1().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "sample_projectname.db_table1.field1");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->field1(), output);
  }

  // optional string field2 = 2;
  if (has_field2()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->field2().data(), this->field2().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "sample_projectname.db_table1.field2");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->field2(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:sample_projectname.db_table1)
}

::google::protobuf::uint8* db_table1::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:sample_projectname.db_table1)
  // optional string field1 = 1;
  if (has_field1()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->field1().data(), this->field1().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "sample_projectname.db_table1.field1");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->field1(), target);
  }

  // optional string field2 = 2;
  if (has_field2()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->field2().data(), this->field2().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "sample_projectname.db_table1.field2");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->field2(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sample_projectname.db_table1)
  return target;
}

int db_table1::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & 3) {
    // optional string field1 = 1;
    if (has_field1()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->field1());
    }

    // optional string field2 = 2;
    if (has_field2()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->field2());
    }

  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void db_table1::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const db_table1* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const db_table1*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void db_table1::MergeFrom(const db_table1& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_field1()) {
      set_has_field1();
      field1_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.field1_);
    }
    if (from.has_field2()) {
      set_has_field2();
      field2_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.field2_);
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void db_table1::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void db_table1::CopyFrom(const db_table1& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool db_table1::IsInitialized() const {

  return true;
}

void db_table1::Swap(db_table1* other) {
  if (other == this) return;
  InternalSwap(other);
}
void db_table1::InternalSwap(db_table1* other) {
  field1_.Swap(&other->field1_);
  field2_.Swap(&other->field2_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata db_table1::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = db_table1_descriptor_;
  metadata.reflection = db_table1_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int db_table2::kField1FieldNumber;
const int db_table2::kField2FieldNumber;
#endif  // !_MSC_VER

db_table2::db_table2()
  : ::google::protobuf::Message() , _internal_metadata_(NULL)  {
  SharedCtor();
  // @@protoc_insertion_point(constructor:sample_projectname.db_table2)
}

void db_table2::InitAsDefaultInstance() {
}

db_table2::db_table2(const db_table2& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:sample_projectname.db_table2)
}

void db_table2::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  field1_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  field2_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

db_table2::~db_table2() {
  // @@protoc_insertion_point(destructor:sample_projectname.db_table2)
  SharedDtor();
}

void db_table2::SharedDtor() {
  field1_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  field2_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void db_table2::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* db_table2::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return db_table2_descriptor_;
}

const db_table2& db_table2::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_model_5fdb_2eproto();
  return *default_instance_;
}

db_table2* db_table2::default_instance_ = NULL;

db_table2* db_table2::New(::google::protobuf::Arena* arena) const {
  db_table2* n = new db_table2;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void db_table2::Clear() {
  if (_has_bits_[0 / 32] & 3) {
    if (has_field1()) {
      field1_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_field2()) {
      field2_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool db_table2::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:sample_projectname.db_table2)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string field1 = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_field1()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->field1().data(), this->field1().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "sample_projectname.db_table2.field1");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_field2;
        break;
      }

      // optional string field2 = 2;
      case 2: {
        if (tag == 18) {
         parse_field2:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_field2()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->field2().data(), this->field2().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "sample_projectname.db_table2.field2");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:sample_projectname.db_table2)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:sample_projectname.db_table2)
  return false;
#undef DO_
}

void db_table2::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:sample_projectname.db_table2)
  // optional string field1 = 1;
  if (has_field1()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->field1().data(), this->field1().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "sample_projectname.db_table2.field1");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->field1(), output);
  }

  // optional string field2 = 2;
  if (has_field2()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->field2().data(), this->field2().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "sample_projectname.db_table2.field2");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->field2(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:sample_projectname.db_table2)
}

::google::protobuf::uint8* db_table2::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:sample_projectname.db_table2)
  // optional string field1 = 1;
  if (has_field1()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->field1().data(), this->field1().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "sample_projectname.db_table2.field1");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->field1(), target);
  }

  // optional string field2 = 2;
  if (has_field2()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->field2().data(), this->field2().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "sample_projectname.db_table2.field2");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->field2(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sample_projectname.db_table2)
  return target;
}

int db_table2::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & 3) {
    // optional string field1 = 1;
    if (has_field1()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->field1());
    }

    // optional string field2 = 2;
    if (has_field2()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->field2());
    }

  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void db_table2::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const db_table2* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const db_table2*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void db_table2::MergeFrom(const db_table2& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_field1()) {
      set_has_field1();
      field1_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.field1_);
    }
    if (from.has_field2()) {
      set_has_field2();
      field2_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.field2_);
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void db_table2::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void db_table2::CopyFrom(const db_table2& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool db_table2::IsInitialized() const {

  return true;
}

void db_table2::Swap(db_table2* other) {
  if (other == this) return;
  InternalSwap(other);
}
void db_table2::InternalSwap(db_table2* other) {
  field1_.Swap(&other->field1_);
  field2_.Swap(&other->field2_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata db_table2::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = db_table2_descriptor_;
  metadata.reflection = db_table2_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int db_table3::kField1FieldNumber;
const int db_table3::kField2FieldNumber;
const int db_table3::kField3FieldNumber;
#endif  // !_MSC_VER

db_table3::db_table3()
  : ::google::protobuf::Message() , _internal_metadata_(NULL)  {
  SharedCtor();
  // @@protoc_insertion_point(constructor:sample_projectname.db_table3)
}

void db_table3::InitAsDefaultInstance() {
}

db_table3::db_table3(const db_table3& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:sample_projectname.db_table3)
}

void db_table3::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  field1_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  field2_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  field3_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

db_table3::~db_table3() {
  // @@protoc_insertion_point(destructor:sample_projectname.db_table3)
  SharedDtor();
}

void db_table3::SharedDtor() {
  field1_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  field2_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  field3_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void db_table3::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* db_table3::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return db_table3_descriptor_;
}

const db_table3& db_table3::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_model_5fdb_2eproto();
  return *default_instance_;
}

db_table3* db_table3::default_instance_ = NULL;

db_table3* db_table3::New(::google::protobuf::Arena* arena) const {
  db_table3* n = new db_table3;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void db_table3::Clear() {
  if (_has_bits_[0 / 32] & 7) {
    if (has_field1()) {
      field1_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_field2()) {
      field2_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_field3()) {
      field3_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool db_table3::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:sample_projectname.db_table3)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string field1 = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_field1()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->field1().data(), this->field1().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "sample_projectname.db_table3.field1");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_field2;
        break;
      }

      // optional string field2 = 2;
      case 2: {
        if (tag == 18) {
         parse_field2:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_field2()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->field2().data(), this->field2().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "sample_projectname.db_table3.field2");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_field3;
        break;
      }

      // optional string field3 = 3;
      case 3: {
        if (tag == 26) {
         parse_field3:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_field3()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->field3().data(), this->field3().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "sample_projectname.db_table3.field3");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:sample_projectname.db_table3)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:sample_projectname.db_table3)
  return false;
#undef DO_
}

void db_table3::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:sample_projectname.db_table3)
  // optional string field1 = 1;
  if (has_field1()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->field1().data(), this->field1().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "sample_projectname.db_table3.field1");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->field1(), output);
  }

  // optional string field2 = 2;
  if (has_field2()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->field2().data(), this->field2().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "sample_projectname.db_table3.field2");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->field2(), output);
  }

  // optional string field3 = 3;
  if (has_field3()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->field3().data(), this->field3().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "sample_projectname.db_table3.field3");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->field3(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:sample_projectname.db_table3)
}

::google::protobuf::uint8* db_table3::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:sample_projectname.db_table3)
  // optional string field1 = 1;
  if (has_field1()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->field1().data(), this->field1().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "sample_projectname.db_table3.field1");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->field1(), target);
  }

  // optional string field2 = 2;
  if (has_field2()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->field2().data(), this->field2().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "sample_projectname.db_table3.field2");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->field2(), target);
  }

  // optional string field3 = 3;
  if (has_field3()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->field3().data(), this->field3().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "sample_projectname.db_table3.field3");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->field3(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sample_projectname.db_table3)
  return target;
}

int db_table3::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & 7) {
    // optional string field1 = 1;
    if (has_field1()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->field1());
    }

    // optional string field2 = 2;
    if (has_field2()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->field2());
    }

    // optional string field3 = 3;
    if (has_field3()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->field3());
    }

  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void db_table3::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const db_table3* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const db_table3*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void db_table3::MergeFrom(const db_table3& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_field1()) {
      set_has_field1();
      field1_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.field1_);
    }
    if (from.has_field2()) {
      set_has_field2();
      field2_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.field2_);
    }
    if (from.has_field3()) {
      set_has_field3();
      field3_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.field3_);
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void db_table3::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void db_table3::CopyFrom(const db_table3& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool db_table3::IsInitialized() const {

  return true;
}

void db_table3::Swap(db_table3* other) {
  if (other == this) return;
  InternalSwap(other);
}
void db_table3::InternalSwap(db_table3* other) {
  field1_.Swap(&other->field1_);
  field2_.Swap(&other->field2_);
  field3_.Swap(&other->field3_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata db_table3::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = db_table3_descriptor_;
  metadata.reflection = db_table3_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int db_table4::kField1FieldNumber;
const int db_table4::kField2FieldNumber;
const int db_table4::kField3FieldNumber;
const int db_table4::kField4FieldNumber;
#endif  // !_MSC_VER

db_table4::db_table4()
  : ::google::protobuf::Message() , _internal_metadata_(NULL)  {
  SharedCtor();
  // @@protoc_insertion_point(constructor:sample_projectname.db_table4)
}

void db_table4::InitAsDefaultInstance() {
}

db_table4::db_table4(const db_table4& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:sample_projectname.db_table4)
}

void db_table4::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  field1_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  field2_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  field3_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  field4_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

db_table4::~db_table4() {
  // @@protoc_insertion_point(destructor:sample_projectname.db_table4)
  SharedDtor();
}

void db_table4::SharedDtor() {
  field1_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  field2_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  field3_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  field4_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void db_table4::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* db_table4::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return db_table4_descriptor_;
}

const db_table4& db_table4::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_model_5fdb_2eproto();
  return *default_instance_;
}

db_table4* db_table4::default_instance_ = NULL;

db_table4* db_table4::New(::google::protobuf::Arena* arena) const {
  db_table4* n = new db_table4;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void db_table4::Clear() {
  if (_has_bits_[0 / 32] & 15) {
    if (has_field1()) {
      field1_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_field2()) {
      field2_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_field3()) {
      field3_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_field4()) {
      field4_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool db_table4::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:sample_projectname.db_table4)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string field1 = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_field1()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->field1().data(), this->field1().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "sample_projectname.db_table4.field1");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_field2;
        break;
      }

      // optional string field2 = 2;
      case 2: {
        if (tag == 18) {
         parse_field2:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_field2()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->field2().data(), this->field2().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "sample_projectname.db_table4.field2");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_field3;
        break;
      }

      // optional string field3 = 3;
      case 3: {
        if (tag == 26) {
         parse_field3:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_field3()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->field3().data(), this->field3().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "sample_projectname.db_table4.field3");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_field4;
        break;
      }

      // optional string field4 = 4;
      case 4: {
        if (tag == 34) {
         parse_field4:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_field4()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->field4().data(), this->field4().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "sample_projectname.db_table4.field4");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:sample_projectname.db_table4)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:sample_projectname.db_table4)
  return false;
#undef DO_
}

void db_table4::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:sample_projectname.db_table4)
  // optional string field1 = 1;
  if (has_field1()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->field1().data(), this->field1().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "sample_projectname.db_table4.field1");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->field1(), output);
  }

  // optional string field2 = 2;
  if (has_field2()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->field2().data(), this->field2().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "sample_projectname.db_table4.field2");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->field2(), output);
  }

  // optional string field3 = 3;
  if (has_field3()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->field3().data(), this->field3().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "sample_projectname.db_table4.field3");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->field3(), output);
  }

  // optional string field4 = 4;
  if (has_field4()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->field4().data(), this->field4().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "sample_projectname.db_table4.field4");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->field4(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:sample_projectname.db_table4)
}

::google::protobuf::uint8* db_table4::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:sample_projectname.db_table4)
  // optional string field1 = 1;
  if (has_field1()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->field1().data(), this->field1().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "sample_projectname.db_table4.field1");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->field1(), target);
  }

  // optional string field2 = 2;
  if (has_field2()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->field2().data(), this->field2().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "sample_projectname.db_table4.field2");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->field2(), target);
  }

  // optional string field3 = 3;
  if (has_field3()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->field3().data(), this->field3().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "sample_projectname.db_table4.field3");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->field3(), target);
  }

  // optional string field4 = 4;
  if (has_field4()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->field4().data(), this->field4().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "sample_projectname.db_table4.field4");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->field4(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sample_projectname.db_table4)
  return target;
}

int db_table4::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & 15) {
    // optional string field1 = 1;
    if (has_field1()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->field1());
    }

    // optional string field2 = 2;
    if (has_field2()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->field2());
    }

    // optional string field3 = 3;
    if (has_field3()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->field3());
    }

    // optional string field4 = 4;
    if (has_field4()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->field4());
    }

  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void db_table4::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const db_table4* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const db_table4*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void db_table4::MergeFrom(const db_table4& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_field1()) {
      set_has_field1();
      field1_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.field1_);
    }
    if (from.has_field2()) {
      set_has_field2();
      field2_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.field2_);
    }
    if (from.has_field3()) {
      set_has_field3();
      field3_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.field3_);
    }
    if (from.has_field4()) {
      set_has_field4();
      field4_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.field4_);
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void db_table4::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void db_table4::CopyFrom(const db_table4& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool db_table4::IsInitialized() const {

  return true;
}

void db_table4::Swap(db_table4* other) {
  if (other == this) return;
  InternalSwap(other);
}
void db_table4::InternalSwap(db_table4* other) {
  field1_.Swap(&other->field1_);
  field2_.Swap(&other->field2_);
  field3_.Swap(&other->field3_);
  field4_.Swap(&other->field4_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata db_table4::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = db_table4_descriptor_;
  metadata.reflection = db_table4_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int db_table5::kField1FieldNumber;
const int db_table5::kField2FieldNumber;
const int db_table5::kField3FieldNumber;
const int db_table5::kField4FieldNumber;
const int db_table5::kField5FieldNumber;
#endif  // !_MSC_VER

db_table5::db_table5()
  : ::google::protobuf::Message() , _internal_metadata_(NULL)  {
  SharedCtor();
  // @@protoc_insertion_point(constructor:sample_projectname.db_table5)
}

void db_table5::InitAsDefaultInstance() {
}

db_table5::db_table5(const db_table5& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:sample_projectname.db_table5)
}

void db_table5::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  field1_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  field2_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  field3_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  field4_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  field5_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

db_table5::~db_table5() {
  // @@protoc_insertion_point(destructor:sample_projectname.db_table5)
  SharedDtor();
}

void db_table5::SharedDtor() {
  field1_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  field2_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  field3_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  field4_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  field5_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void db_table5::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* db_table5::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return db_table5_descriptor_;
}

const db_table5& db_table5::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_model_5fdb_2eproto();
  return *default_instance_;
}

db_table5* db_table5::default_instance_ = NULL;

db_table5* db_table5::New(::google::protobuf::Arena* arena) const {
  db_table5* n = new db_table5;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void db_table5::Clear() {
  if (_has_bits_[0 / 32] & 31) {
    if (has_field1()) {
      field1_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_field2()) {
      field2_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_field3()) {
      field3_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_field4()) {
      field4_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_field5()) {
      field5_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool db_table5::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:sample_projectname.db_table5)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string field1 = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_field1()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->field1().data(), this->field1().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "sample_projectname.db_table5.field1");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_field2;
        break;
      }

      // optional string field2 = 2;
      case 2: {
        if (tag == 18) {
         parse_field2:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_field2()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->field2().data(), this->field2().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "sample_projectname.db_table5.field2");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_field3;
        break;
      }

      // optional string field3 = 3;
      case 3: {
        if (tag == 26) {
         parse_field3:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_field3()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->field3().data(), this->field3().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "sample_projectname.db_table5.field3");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_field4;
        break;
      }

      // optional string field4 = 4;
      case 4: {
        if (tag == 34) {
         parse_field4:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_field4()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->field4().data(), this->field4().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "sample_projectname.db_table5.field4");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_field5;
        break;
      }

      // optional string field5 = 5;
      case 5: {
        if (tag == 42) {
         parse_field5:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_field5()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->field5().data(), this->field5().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "sample_projectname.db_table5.field5");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:sample_projectname.db_table5)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:sample_projectname.db_table5)
  return false;
#undef DO_
}

void db_table5::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:sample_projectname.db_table5)
  // optional string field1 = 1;
  if (has_field1()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->field1().data(), this->field1().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "sample_projectname.db_table5.field1");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->field1(), output);
  }

  // optional string field2 = 2;
  if (has_field2()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->field2().data(), this->field2().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "sample_projectname.db_table5.field2");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->field2(), output);
  }

  // optional string field3 = 3;
  if (has_field3()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->field3().data(), this->field3().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "sample_projectname.db_table5.field3");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->field3(), output);
  }

  // optional string field4 = 4;
  if (has_field4()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->field4().data(), this->field4().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "sample_projectname.db_table5.field4");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->field4(), output);
  }

  // optional string field5 = 5;
  if (has_field5()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->field5().data(), this->field5().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "sample_projectname.db_table5.field5");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->field5(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:sample_projectname.db_table5)
}

::google::protobuf::uint8* db_table5::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:sample_projectname.db_table5)
  // optional string field1 = 1;
  if (has_field1()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->field1().data(), this->field1().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "sample_projectname.db_table5.field1");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->field1(), target);
  }

  // optional string field2 = 2;
  if (has_field2()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->field2().data(), this->field2().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "sample_projectname.db_table5.field2");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->field2(), target);
  }

  // optional string field3 = 3;
  if (has_field3()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->field3().data(), this->field3().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "sample_projectname.db_table5.field3");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->field3(), target);
  }

  // optional string field4 = 4;
  if (has_field4()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->field4().data(), this->field4().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "sample_projectname.db_table5.field4");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->field4(), target);
  }

  // optional string field5 = 5;
  if (has_field5()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->field5().data(), this->field5().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "sample_projectname.db_table5.field5");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->field5(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sample_projectname.db_table5)
  return target;
}

int db_table5::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & 31) {
    // optional string field1 = 1;
    if (has_field1()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->field1());
    }

    // optional string field2 = 2;
    if (has_field2()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->field2());
    }

    // optional string field3 = 3;
    if (has_field3()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->field3());
    }

    // optional string field4 = 4;
    if (has_field4()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->field4());
    }

    // optional string field5 = 5;
    if (has_field5()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->field5());
    }

  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void db_table5::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const db_table5* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const db_table5*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void db_table5::MergeFrom(const db_table5& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_field1()) {
      set_has_field1();
      field1_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.field1_);
    }
    if (from.has_field2()) {
      set_has_field2();
      field2_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.field2_);
    }
    if (from.has_field3()) {
      set_has_field3();
      field3_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.field3_);
    }
    if (from.has_field4()) {
      set_has_field4();
      field4_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.field4_);
    }
    if (from.has_field5()) {
      set_has_field5();
      field5_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.field5_);
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void db_table5::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void db_table5::CopyFrom(const db_table5& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool db_table5::IsInitialized() const {

  return true;
}

void db_table5::Swap(db_table5* other) {
  if (other == this) return;
  InternalSwap(other);
}
void db_table5::InternalSwap(db_table5* other) {
  field1_.Swap(&other->field1_);
  field2_.Swap(&other->field2_);
  field3_.Swap(&other->field3_);
  field4_.Swap(&other->field4_);
  field5_.Swap(&other->field5_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata db_table5::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = db_table5_descriptor_;
  metadata.reflection = db_table5_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace sample_projectname

// @@protoc_insertion_point(global_scope)
